"""empty message

Revision ID: 63403fd141ad
Revises: 
Create Date: 2021-05-16 23:56:32.258967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63403fd141ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('MemeTemplate',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_MemeTemplate_title'), 'MemeTemplate', ['title'], unique=True)
    op.create_table('MemeTemplateImage',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meme_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meme_template_id'], ['MemeTemplate.pk'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'meme_template_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MemeTemplateImage')
    op.drop_index(op.f('ix_MemeTemplate_title'), table_name='MemeTemplate')
    op.drop_table('MemeTemplate')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
