"""empty message

Revision ID: 801573a9f2b3
Revises: 
Create Date: 2021-05-26 21:51:28.344875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801573a9f2b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('MemeTemplate',
    sa.Column('image_path', sa.String(length=128), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('title', 'owner_id', name='user_uniq_template')
    )
    op.create_index(op.f('ix_MemeTemplate_title'), 'MemeTemplate', ['title'], unique=False)
    op.create_table('Meme',
    sa.Column('image_path', sa.String(length=128), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.pk'], ),
    sa.ForeignKeyConstraint(['template_id'], ['MemeTemplate.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Meme')
    op.drop_index(op.f('ix_MemeTemplate_title'), table_name='MemeTemplate')
    op.drop_table('MemeTemplate')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
