"""empty message

Revision ID: e2c3ae6b4f62
Revises: 63403fd141ad
Create Date: 2021-05-17 16:57:21.083648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c3ae6b4f62'
down_revision = '63403fd141ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MemeTemplateImage')
    op.drop_index('ix_MemeTemplate_title', table_name='MemeTemplate')
    op.drop_table('MemeTemplate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MemeTemplate',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index('ix_MemeTemplate_title', 'MemeTemplate', ['title'], unique=False)
    op.create_table('MemeTemplateImage',
    sa.Column('width', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('mimetype', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('meme_template_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['meme_template_id'], ['MemeTemplate.pk'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'meme_template_id')
    )
    # ### end Alembic commands ###
