"""empty message

Revision ID: f36d74ac1822
Revises: 3408793f3885
Create Date: 2021-05-19 21:43:27.278039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36d74ac1822'
down_revision = '3408793f3885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Meme',
    sa.Column('image_path', sa.String(length=128), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.pk'], ),
    sa.ForeignKeyConstraint(['template_id'], ['MemeTemplate.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Meme')
    # ### end Alembic commands ###
